# Perfil alternativo cuando el puerto 8080 está ocupado.
# PowerShell: mvn spring-boot:run "-Dspring-boot.run.arguments=--spring.profiles.active=altport"
# CMD:        mvn spring-boot:run -Dspring-boot.run.arguments="--spring.profiles.active=altport"
# Si usas este perfil, en el frontend (sigea-frontend/proxy.conf.json) cambia "target" a "http://localhost:8081"
server.port=8081
